name: TicTacToe
description: Simple TicTacToe game for 2 players on one screen
publish_to: 'none'

version: 1.2.0+3

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  touchable: ^1.0.2 # for easy gesture detection on canvas

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
